server:
  port: 7777
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.28.4.17
  client:
    serviceUrl:
      defaultZone: http://192.28.4.23:8761/eureka/,http://192.28.4.24:8761/eureka/,http://192.28.4.25:8761/eureka/
    eureka-server-connect-timeout-seconds: 10
    eureka-server-read-timeout-seconds: 20
    registry-fetch-interval-seconds: 10
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
logging:
  level:
    org.springframework.cloud.gateway: debug