server:
  port: 8081
  shutdown: graceful
spring:
  application:
    name: echo-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}
management:
  endpoint:
    pause:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: pause,restart