server:
  port: 8081
  shutdown: graceful
spring:
  application:
    name: echo-client
  lifecycle:
    timeout-per-shutdown-phase: 20s
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
management:
  endpoint:
    pause:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: pause,restart