server:
  port: 8080
spring:
  application:
    name: echo-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}